### ISSUE TITLE
请问cannylines的源码你是从哪里获取的，我去作者官网发现已经没有链接了

### ISSUE THREAD

**Issue by Yanjiqiang** [Gofinge/cannyline-pybind#1]

**Comment by Gofinge** [comment]
![image](https://user-images.githubusercontent.com/39218229/149616215-82daff86-fb01-46bb-b73a-0111acf310a5.png)
[https://cvrs.whu.edu.cn/cannylines/](url)

**Comment by Yanjiqiang** [comment]
十分感谢
